/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bigbull.views;

import com.bigbull.models.BigBullDataModel;
import com.bigbull.utils.BigBullUtilities;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Objects;

/**
 * The BigBull class represents the main frame of the application. It includes
 * methods for initializing the form, applying custom settings, and updating the
 * table. The table displays financial transactions using the DataModel class
 * and interacts with the Utilities class for data manipulation.
 *
 * @author dklku
 */
public class BigBull extends javax.swing.JFrame {

    /**
     * Creates a new instance of the BigBull class. Initializes the form,
     * applies custom settings, and updates the table.
     */
    public BigBull() {
        initComponents();
        mySettings();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortButtonGroup = new javax.swing.ButtonGroup();
        mainJPanel = new javax.swing.JPanel();
        headerJPanel = new javax.swing.JPanel();
        logoJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        headerJLabel = new javax.swing.JLabel();
        midJPanel = new javax.swing.JPanel();
        searchJLabel = new javax.swing.JLabel();
        searchJPanel = new javax.swing.JPanel();
        searchJTextField = new javax.swing.JTextField();
        searchJButton = new javax.swing.JButton();
        cancelSearchJButton = new javax.swing.JButton();
        filterJPanel = new javax.swing.JPanel();
        sortJPanel = new javax.swing.JPanel();
        sortJLabel = new javax.swing.JLabel();
        ascendingJRadioButton = new javax.swing.JRadioButton();
        descendingJRadioButton = new javax.swing.JRadioButton();
        sortJComboBox = new javax.swing.JComboBox<>();
        sortJPanel2 = new javax.swing.JPanel();
        sortJLabel2 = new javax.swing.JLabel();
        sectorJComboBox = new javax.swing.JComboBox<>();
        sortJPanel1 = new javax.swing.JPanel();
        sortJLabel1 = new javax.swing.JLabel();
        transactionTypeJComboBox = new javax.swing.JComboBox<>();
        tableJPanel = new javax.swing.JPanel();
        tableJScrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bottomJPanel = new javax.swing.JPanel();
        updateEntryJButton = new javax.swing.JButton();
        deleteEntryJButton = new javax.swing.JButton();
        addEntryJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 832));
        setName("mainJFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        mainJPanel.setBackground(new java.awt.Color(217, 217, 217));
        mainJPanel.setMinimumSize(new java.awt.Dimension(1280, 832));
        mainJPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        mainJPanel.setRequestFocusEnabled(false);

        headerJPanel.setBackground(new java.awt.Color(246, 250, 253));
        headerJPanel.setFocusCycleRoot(true);
        headerJPanel.setMaximumSize(new java.awt.Dimension(1280, 118));
        headerJPanel.setMinimumSize(new java.awt.Dimension(1280, 118));
        headerJPanel.setName(""); // NOI18N
        headerJPanel.setPreferredSize(new java.awt.Dimension(1280, 118));

        logoJPanel.setMaximumSize(new java.awt.Dimension(118, 118));
        logoJPanel.setMinimumSize(new java.awt.Dimension(118, 118));
        logoJPanel.setName(""); // NOI18N
        logoJPanel.setPreferredSize(new java.awt.Dimension(118, 118));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bigbull/views/assets/Logo_118.png"))); // NOI18N

        javax.swing.GroupLayout logoJPanelLayout = new javax.swing.GroupLayout(logoJPanel);
        logoJPanel.setLayout(logoJPanelLayout);
        logoJPanelLayout.setHorizontalGroup(
            logoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
            .addGroup(logoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logoJPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        logoJPanelLayout.setVerticalGroup(
            logoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
            .addGroup(logoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(logoJPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        headerJLabel.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
        headerJLabel.setForeground(new java.awt.Color(9, 44, 76));
        headerJLabel.setText("BigBull: Your Personal Stock Logbook");
        headerJLabel.setAlignmentX(0.5F);

        javax.swing.GroupLayout headerJPanelLayout = new javax.swing.GroupLayout(headerJPanel);
        headerJPanel.setLayout(headerJPanelLayout);
        headerJPanelLayout.setHorizontalGroup(
            headerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerJPanelLayout.createSequentialGroup()
                .addComponent(logoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(headerJLabel)
                .addGap(0, 552, Short.MAX_VALUE))
        );
        headerJPanelLayout.setVerticalGroup(
            headerJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerJPanelLayout.createSequentialGroup()
                .addComponent(logoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerJLabel)
                .addGap(37, 37, 37))
        );

        midJPanel.setBackground(new java.awt.Color(217, 217, 217));
        midJPanel.setMaximumSize(new java.awt.Dimension(1100, 98));
        midJPanel.setMinimumSize(new java.awt.Dimension(1100, 98));
        midJPanel.setPreferredSize(new java.awt.Dimension(1100, 98));

        searchJLabel.setBackground(new java.awt.Color(9, 44, 76));
        searchJLabel.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        searchJLabel.setText("Search by Symbol");

        searchJPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchJPanel.setMaximumSize(new java.awt.Dimension(350, 50));
        searchJPanel.setMinimumSize(new java.awt.Dimension(350, 50));
        searchJPanel.setPreferredSize(new java.awt.Dimension(350, 50));

        searchJTextField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        searchJTextField.setForeground(new java.awt.Color(9, 44, 76));
        searchJTextField.setBorder(null);

        searchJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bigbull/views/assets/Search_Icon.png"))); // NOI18N
        searchJButton.setBorder(null);
        searchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchJButtonActionPerformed(evt);
            }
        });

        cancelSearchJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bigbull/views/assets/Cancel_Icon.png"))); // NOI18N
        cancelSearchJButton.setBorder(null);
        cancelSearchJButton.setOpaque(true);
        cancelSearchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSearchJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchJPanelLayout = new javax.swing.GroupLayout(searchJPanel);
        searchJPanel.setLayout(searchJPanelLayout);
        searchJPanelLayout.setHorizontalGroup(
            searchJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(searchJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchJPanelLayout.createSequentialGroup()
                    .addGap(0, 291, Short.MAX_VALUE)
                    .addComponent(searchJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(searchJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchJPanelLayout.createSequentialGroup()
                    .addContainerGap(233, Short.MAX_VALUE)
                    .addComponent(cancelSearchJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );
        searchJPanelLayout.setVerticalGroup(
            searchJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(searchJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(searchJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
            .addGroup(searchJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cancelSearchJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        sortJPanel.setBackground(new java.awt.Color(255, 255, 255));
        sortJPanel.setMaximumSize(new java.awt.Dimension(350, 50));
        sortJPanel.setMinimumSize(new java.awt.Dimension(350, 50));
        sortJPanel.setOpaque(false);

        sortJLabel.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        sortJLabel.setForeground(new java.awt.Color(9, 44, 76));
        sortJLabel.setText("Sort By:");

        sortButtonGroup.add(ascendingJRadioButton);
        ascendingJRadioButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        ascendingJRadioButton.setForeground(new java.awt.Color(9, 44, 76));
        ascendingJRadioButton.setSelected(true);
        ascendingJRadioButton.setText("Ascending");
        ascendingJRadioButton.setToolTipText("");
        ascendingJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ascendingJRadioButtonActionPerformed(evt);
            }
        });

        sortButtonGroup.add(descendingJRadioButton);
        descendingJRadioButton.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        descendingJRadioButton.setForeground(new java.awt.Color(9, 44, 76));
        descendingJRadioButton.setText("Descending");
        descendingJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descendingJRadioButtonActionPerformed(evt);
            }
        });

        sortJComboBox.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        sortJComboBox.setForeground(new java.awt.Color(9, 44, 76));
        sortJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Symbol No.", "Date", "Price per Share", "Quantity", "Total Amount" }));
        sortJComboBox.setBorder(null);
        sortJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortJComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sortJPanelLayout = new javax.swing.GroupLayout(sortJPanel);
        sortJPanel.setLayout(sortJPanelLayout);
        sortJPanelLayout.setHorizontalGroup(
            sortJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortJPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(sortJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sortJPanelLayout.createSequentialGroup()
                        .addComponent(ascendingJRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descendingJRadioButton))
                    .addGroup(sortJPanelLayout.createSequentialGroup()
                        .addComponent(sortJLabel)
                        .addGap(18, 18, 18)
                        .addComponent(sortJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sortJPanelLayout.setVerticalGroup(
            sortJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sortJPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(sortJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortJLabel)
                    .addComponent(sortJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sortJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descendingJRadioButton)
                    .addComponent(ascendingJRadioButton))
                .addContainerGap())
        );

        sortJPanel2.setBackground(new java.awt.Color(255, 255, 255));
        sortJPanel2.setMaximumSize(new java.awt.Dimension(350, 50));
        sortJPanel2.setMinimumSize(new java.awt.Dimension(350, 50));
        sortJPanel2.setOpaque(false);

        sortJLabel2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        sortJLabel2.setForeground(new java.awt.Color(9, 44, 76));
        sortJLabel2.setText("Sector");

        sectorJComboBox.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        sectorJComboBox.setForeground(new java.awt.Color(9, 44, 76));
        sectorJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Bank", "Hydropower", "Insurance", "Finance", "Investment", "Trading", "Other" }));
        sectorJComboBox.setBorder(null);
        sectorJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectorJComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sortJPanel2Layout = new javax.swing.GroupLayout(sortJPanel2);
        sortJPanel2.setLayout(sortJPanel2Layout);
        sortJPanel2Layout.setHorizontalGroup(
            sortJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortJPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sortJLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sectorJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        sortJPanel2Layout.setVerticalGroup(
            sortJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sortJPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(sortJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortJLabel2)
                    .addComponent(sectorJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        sortJPanel1.setBackground(new java.awt.Color(255, 255, 255));
        sortJPanel1.setMaximumSize(new java.awt.Dimension(350, 50));
        sortJPanel1.setMinimumSize(new java.awt.Dimension(350, 50));
        sortJPanel1.setOpaque(false);

        sortJLabel1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        sortJLabel1.setForeground(new java.awt.Color(9, 44, 76));
        sortJLabel1.setText("Transaction Type");

        transactionTypeJComboBox.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        transactionTypeJComboBox.setForeground(new java.awt.Color(9, 44, 76));
        transactionTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Buy", "Sell" }));
        transactionTypeJComboBox.setBorder(null);
        transactionTypeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionTypeJComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sortJPanel1Layout = new javax.swing.GroupLayout(sortJPanel1);
        sortJPanel1.setLayout(sortJPanel1Layout);
        sortJPanel1Layout.setHorizontalGroup(
            sortJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortJPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(sortJLabel1)
                .addGap(18, 18, 18)
                .addComponent(transactionTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sortJPanel1Layout.setVerticalGroup(
            sortJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sortJPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sortJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transactionTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout filterJPanelLayout = new javax.swing.GroupLayout(filterJPanel);
        filterJPanel.setLayout(filterJPanelLayout);
        filterJPanelLayout.setHorizontalGroup(
            filterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filterJPanelLayout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addComponent(sortJPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(filterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(filterJPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sortJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(331, Short.MAX_VALUE)))
            .addGroup(filterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(filterJPanelLayout.createSequentialGroup()
                    .addGap(255, 255, 255)
                    .addComponent(sortJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );
        filterJPanelLayout.setVerticalGroup(
            filterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filterJPanelLayout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(sortJPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(filterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filterJPanelLayout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(sortJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(filterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(filterJPanelLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(sortJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout midJPanelLayout = new javax.swing.GroupLayout(midJPanel);
        midJPanel.setLayout(midJPanelLayout);
        midJPanelLayout.setHorizontalGroup(
            midJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midJPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(midJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filterJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        midJPanelLayout.setVerticalGroup(
            midJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(midJPanelLayout.createSequentialGroup()
                .addGroup(midJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(midJPanelLayout.createSequentialGroup()
                        .addComponent(searchJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(filterJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        tableJPanel.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        tableJScrollPane.setPreferredSize(new java.awt.Dimension(1050, 3900));

        table.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.N.", "Date", "Symbol", "Transaction Type", "Price per Share", "Quantity", "Total Amount", "Transaction Fees", "Total after Fees", "Sector", "Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setPreferredSize(new java.awt.Dimension(1050, 1000));
        table.setRowHeight(40);
        table.setShowGrid(false);
        table.getTableHeader().setResizingAllowed(false);
        table.getTableHeader().setReorderingAllowed(false);
        tableJScrollPane.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(5);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(1).setPreferredWidth(120);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(5).setResizable(false);
            table.getColumnModel().getColumn(6).setResizable(false);
            table.getColumnModel().getColumn(7).setResizable(false);
            table.getColumnModel().getColumn(8).setResizable(false);
            table.getColumnModel().getColumn(9).setResizable(false);
            table.getColumnModel().getColumn(10).setResizable(false);
            table.getColumnModel().getColumn(10).setPreferredWidth(150);
        }

        javax.swing.GroupLayout tableJPanelLayout = new javax.swing.GroupLayout(tableJPanel);
        tableJPanel.setLayout(tableJPanelLayout);
        tableJPanelLayout.setHorizontalGroup(
            tableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tableJPanelLayout.setVerticalGroup(
            tableJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tableJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        updateEntryJButton.setBackground(new java.awt.Color(233, 117, 0));
        updateEntryJButton.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        updateEntryJButton.setForeground(new java.awt.Color(255, 255, 255));
        updateEntryJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bigbull/views/assets/Plus_Icon.png"))); // NOI18N
        updateEntryJButton.setText("Update Entry");
        updateEntryJButton.setBorder(null);
        updateEntryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEntryJButtonActionPerformed(evt);
            }
        });

        deleteEntryJButton.setBackground(new java.awt.Color(207, 48, 48));
        deleteEntryJButton.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        deleteEntryJButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteEntryJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bigbull/views/assets/Plus_Icon.png"))); // NOI18N
        deleteEntryJButton.setText("Delete Entry");
        deleteEntryJButton.setBorder(null);
        deleteEntryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEntryJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomJPanelLayout = new javax.swing.GroupLayout(bottomJPanel);
        bottomJPanel.setLayout(bottomJPanelLayout);
        bottomJPanelLayout.setHorizontalGroup(
            bottomJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomJPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(updateEntryJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(deleteEntryJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        bottomJPanelLayout.setVerticalGroup(
            bottomJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomJPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(bottomJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateEntryJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteEntryJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        addEntryJButton.setBackground(new java.awt.Color(0, 157, 119));
        addEntryJButton.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        addEntryJButton.setForeground(new java.awt.Color(255, 255, 255));
        addEntryJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bigbull/views/assets/Plus_Icon.png"))); // NOI18N
        addEntryJButton.setText("Add Entry");
        addEntryJButton.setBorder(null);
        addEntryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEntryJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainJPanelLayout = new javax.swing.GroupLayout(mainJPanel);
        mainJPanel.setLayout(mainJPanelLayout);
        mainJPanelLayout.setHorizontalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainJPanelLayout.createSequentialGroup()
                        .addComponent(midJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1088, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addEntryJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(bottomJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainJPanelLayout.setVerticalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addComponent(headerJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainJPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(addEntryJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(midJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addComponent(tableJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bottomJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descendingJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descendingJRadioButtonActionPerformed
        updateTable();
    }//GEN-LAST:event_descendingJRadioButtonActionPerformed

    private void ascendingJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ascendingJRadioButtonActionPerformed
        updateTable();
    }//GEN-LAST:event_ascendingJRadioButtonActionPerformed

    private void sortJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortJComboBoxActionPerformed
        updateTable();
    }//GEN-LAST:event_sortJComboBoxActionPerformed

    /**
     * Handles the action event when the cancel search button is clicked. Clears
     * the search text field, hides the cancel search button, and updates the
     * table.
     *
     * @param evt The ActionEvent triggered by the cancel search button click.
     */
    private void cancelSearchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSearchJButtonActionPerformed
        // Clear the search text field
        searchJTextField.setText("");

        // Hide the cancel search button
        cancelSearchJButton.setVisible(false);

        // Update the table with the original data
        updateTable();
    }//GEN-LAST:event_cancelSearchJButtonActionPerformed

    /**
     * Handles the action event when the update entry button is clicked.
     * Retrieves the selected row's data from the table and opens the Form for
     * updating.
     *
     * @param evt The ActionEvent triggered by the update entry button click.
     */
    private void updateEntryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEntryJButtonActionPerformed
        // Get the table model
        DefaultTableModel tableModel = (DefaultTableModel) table.getModel();

        // Switch based on the number of selected rows
        switch (table.getSelectedRowCount()) {
            case 0 ->
                // Display a warning if no row is selected
                JOptionPane.showMessageDialog(null,
                        "Please select a row to update!",
                        "No Rows Selected!",
                        JOptionPane.WARNING_MESSAGE);
            case 1 -> {
                // If one row is selected, retrieve data and open the update form
                int row = table.getSelectedRow();
                short symbolNo = (Short) tableModel.getValueAt(row, 0);
                String date = (String) tableModel.getValueAt(row, 1);
                String symbol = (String) tableModel.getValueAt(row, 2);
                String transactionType = (String) tableModel.getValueAt(row, 3);
                float pricePerShare = (Float) tableModel.getValueAt(row, 4);
                int quantity = (Integer) tableModel.getValueAt(row, 5);
                float totalAmount = (Float) tableModel.getValueAt(row, 6);
                float fees = (Float) tableModel.getValueAt(row, 7);
                float totalAfterFees = (Float) tableModel.getValueAt(row, 8);
                String sector = (String) tableModel.getValueAt(row, 9);
                String note = (String) tableModel.getValueAt(row, 10);
                BigBullDataModel selectedRowData = new BigBullDataModel(symbolNo,
                        date, symbol, transactionType, pricePerShare, quantity,
                        totalAmount, fees, totalAfterFees, sector, note);

                // Hide the current frame
                this.setVisible(false);

                // Open the update form with the selected row data
                BigBullForm updateForm = new BigBullForm(selectedRowData);
                updateForm.setVisible(true);
            }
            default ->
                // Display a warning if multiple rows are selected
                JOptionPane.showMessageDialog(null,
                        "Please select only one row to update!",
                        "Multiple Rows Selected!",
                        JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_updateEntryJButtonActionPerformed

    /**
     * Handles the action event when the delete entry button is clicked. Deletes
     * the selected row from the table after confirming the deletion with the
     * user.
     *
     * @param evt The ActionEvent triggered by the delete entry button click.
     */
    private void deleteEntryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEntryJButtonActionPerformed
        // Switch based on the number of selected rows
        switch (table.getSelectedRowCount()) {
            case 0 ->
                // Display a warning if no row is selected
                JOptionPane.showMessageDialog(null, "Please select a row to delete!", "No Rows Selected!", JOptionPane.WARNING_MESSAGE);
            case 1 -> {
                // If one row is selected, confirm deletion with the user
                int userConfirmation = JOptionPane.showConfirmDialog(null,
                        "Do you sure want to delete this row? This action is permanent and cannot be reverted!",
                        "Delete Row!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

                if (userConfirmation == JOptionPane.YES_OPTION) {
                    // If the user confirms, delete the selected row
                    DefaultTableModel tableModel = (DefaultTableModel) table.getModel();
                    int rowIndex = table.getSelectedRow();
                    short symbolNoOfRowToDelete = (Short) tableModel.getValueAt(rowIndex, 0);
                    BigBullUtilities.deleteRowFromTable(symbolNoOfRowToDelete);

                    // Update the table after deletion
                    updateTable();
                }
            }
            default ->
                // Display a warning if multiple rows are selected
                JOptionPane.showMessageDialog(null, "Please select only one row to delete!", "Multiple Rows Selected!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteEntryJButtonActionPerformed


    private void transactionTypeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionTypeJComboBoxActionPerformed
        updateTable();
    }//GEN-LAST:event_transactionTypeJComboBoxActionPerformed

    private void sectorJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectorJComboBoxActionPerformed
        updateTable();
    }//GEN-LAST:event_sectorJComboBoxActionPerformed

    /**
     * Handles the action event when the add entry button is clicked. Hides the
     * current frame and opens a new form for adding a new entry.
     *
     * @param evt The ActionEvent triggered by the add entry button click.
     */
    private void addEntryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEntryJButtonActionPerformed
        // Hide the current frame
        this.setVisible(false);

        // Open a new form for adding a new entry
        BigBullForm addForm = new BigBullForm();
        addForm.setVisible(true);
    }//GEN-LAST:event_addEntryJButtonActionPerformed

    /**
     * Handles the action event when the search button is clicked. If the search
     * text field is not blank, shows the cancel search button and updates the
     * table.
     *
     * @param evt The ActionEvent triggered by the search button click.
     */
    private void searchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchJButtonActionPerformed
        // Check if the search text field is not blank
        if (!searchJTextField.getText().isBlank()) {
            // Show the cancel search button
            cancelSearchJButton.setVisible(true);

            // Update the table
            updateTable();
        }
    }//GEN-LAST:event_searchJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BigBull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BigBull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BigBull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BigBull.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BigBull().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEntryJButton;
    private javax.swing.JRadioButton ascendingJRadioButton;
    private javax.swing.JPanel bottomJPanel;
    private javax.swing.JButton cancelSearchJButton;
    private javax.swing.JButton deleteEntryJButton;
    private javax.swing.JRadioButton descendingJRadioButton;
    private javax.swing.JPanel filterJPanel;
    private javax.swing.JLabel headerJLabel;
    private javax.swing.JPanel headerJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel logoJPanel;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JPanel midJPanel;
    private javax.swing.JButton searchJButton;
    private javax.swing.JLabel searchJLabel;
    private javax.swing.JPanel searchJPanel;
    private javax.swing.JTextField searchJTextField;
    private javax.swing.JComboBox<String> sectorJComboBox;
    private javax.swing.ButtonGroup sortButtonGroup;
    private javax.swing.JComboBox<String> sortJComboBox;
    private javax.swing.JLabel sortJLabel;
    private javax.swing.JLabel sortJLabel1;
    private javax.swing.JLabel sortJLabel2;
    private javax.swing.JPanel sortJPanel;
    private javax.swing.JPanel sortJPanel1;
    private javax.swing.JPanel sortJPanel2;
    private javax.swing.JTable table;
    private javax.swing.JPanel tableJPanel;
    private javax.swing.JScrollPane tableJScrollPane;
    private javax.swing.JComboBox<String> transactionTypeJComboBox;
    private javax.swing.JButton updateEntryJButton;
    // End of variables declaration//GEN-END:variables

    /**
     * Applies custom settings when the form is initialized. In this case, sets
     * the visibility of the cancel search button to false.
     */
    private void mySettings() {
        cancelSearchJButton.setVisible(false);
    }

    /**
     * Updates the table with data based on various parameters. Retrieves data
     * from the Utilities class and populates the table. The parameters include
     * transaction type, sector, sort order, sorting direction, and search text.
     */
    private void updateTable() {
        // Populate the table using data from BigBullUtilities class
        BigBullUtilities.populateTable(table,
                Objects.requireNonNull(transactionTypeJComboBox.getSelectedItem()).toString(),
                Objects.requireNonNull(sectorJComboBox.getSelectedItem()).toString(),
                Objects.requireNonNull(sortJComboBox.getSelectedItem()).toString(),
                ascendingJRadioButton.isSelected(),
                searchJTextField.getText());
    }

}
